const BUSINESS_CATEGORIES = [
    "Accounting",
    "Advertising",
    "Agriculture",
    "Architectural",
    "Automotive",
    "Banking",
    "Beauty",
    "Biotechnology",
    "Business",
    "Construction",
    "Consulting",
    "Cosmetics",
    "Design",
    "Education",
    "Energy",
    "Engineering",
    "Entertainment",
    "Fashion",
    "Finance",
    "Food",
    "Health",
    "Hospitality",
    "Insurance",
    "Legal",
    "Manufacturing",
    "Marketing",
    "Media",
    "Medical",
    "Music",
    "Nonprofit",
    "Pharmaceutical",
    "Photography",
    "Real Estate",
    "Retail",
    "Sports",
    "Technology",
    "Telecommunications",
    "Transportation",
    "Travel",
    "Utilities",
    "Web Design",
    "Web Development",
    "Writing",
    "Coffee Shop",
    "Restaurant",
    "Bar",
    "Brewery",
    "Cafe",
    "Food Truck",
    "Bakery",
    "Catering",
    "Grocery Store",
    "Food Delivery",
    "Gym",
    "Yoga Studio",
    "Fitness Center",
    "Personal Training",
    "Physical Therapy",
    "Florist",
    "Landscaping",
    "Gardening",
    "Lawn Care",
    "Pool Cleaning",
    "Pest Control",
    "Cleaning",
    "Home Staging",
    "Interior Design",
    "Home Renovation",
    "Home Inspection",
    "Real Estate Agent",
    "Property Management",
    "Mortgage Broker",
    "Insurance Agent",
    "Financial Planner",
    "Accountant",
    "Lawyer",
    "Legal Services",
    "Consultant",
    "Marketing Agency",
    "Advertising Agency",
    "Public Relations",
    "Event Planning",
    "Graphic Design",
    "Web Design",
    "Web Development",
    "Photographer",
    "Videographer",
    "Musician",
    "Band",
    "DJ",
    "Music Producer",
    "Music Teacher",
    "Music Lessons",
    "Music Studio",
    "Logistics",
    "Delivery",
    "Moving",
    "Storage",
    "Courier",
    "Transportation",
    "Rideshare",
    "Taxi",
    "Car Service",
    "Limo Service",
    "Bus Service",
    "Train Service",
    "Airline",
    "Travel Agent",
    "Travel Agency",
    "Tour Guide",
    "Tour Operator",
    "Tourism",
    "Hotel",
    "Motel",
    "Bed and Breakfast",
    "Vacation Rental",
    "Hostel",
    "Resort",
    "Campground",
    "Ski Resort",
    "Theme Park",
    "Amusement Park",
    "Water Park",
    "Zoo",
    "Aquarium",
    "Museum",
    "Art Gallery",
    "Historical Site",
    "National Park",
    "State Park",
    "City Park",
    "Botanical Garden",
    "Nature Preserve",
    "Wildlife Sanctuary",
    "Nature Center",
    "Planetarium",
    "Observatory",
    "Science Museum",
    "Children's Museum",
    "Natural History Museum",
    "History Museum",
    "Art Museum",
    "Art Studio",
    "Art School",
    "Art Class",
    "Art Workshop",
    "Art Camp",
    "Art Gallery",
    "Art Exhibit",
    "Art Show",
    "Art Fair",
    "Art Festival",
    "Art Walk",
    "Art Tour",
    "Antiques",
    "Collectibles",
    "Vintage",
    "Thrift",
    "Secondhand",
    "Artisan",
    "Handmade",
    "Craft",
    "DIY",
    "Homemade",
    "Local",
    "Small Business",
    "Startup",
    "Entrepreneur",
    "Freelancer",
    "Independent Contractor",
    "Self-Employed",
    "Work From Home",
    "Home-Based Business",
    "Online Business",
    "E-Commerce",
    "Internet Business",
    "Digital Business",
    "Mobile Business",
    "Social Media",
    "Content Marketing",
    "Email Marketing",
    "Search Engine Optimization",
    "Pay-Per-Click Advertising",
    "Affiliate Marketing",
    "Influencer Marketing",
    "Video Marketing",
    "Podcast Marketing",
    "Asset Management",
    "Investment Management",
    "Wealth Management",
    "Financial Planning",
    "Retirement Planning",
    "Estate Planning",
    "Tax Planning",
    "Insurance Planning",
    "Risk Management",
    "Portfolio Management",



]

export default BUSINESS_CATEGORIES;